baseURL = 'https://xxfe.com/'
languageCode = 'en-us'
title = '君自强'

[markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = true
  style = "tango"
  tabWidth = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true